server.port : 8081
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 500
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


  h2:
    console:
      enabled: true
nh:
  juntaek:
    accessToken: aea4f248cce5af78f3cc5c62827bcdf5db1ded061977417a29615b2c3221ceda

logging:
  level:
    org.apache.http: DEBUG

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sellenge?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sellenge-db.cxxtoeaihq4h.us-west-2.rds.amazonaws.com:3306/sellenge-db
    username: sellenge
    password: sellenge
---

